# Generated by Django 5.1.3 on 2024-11-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("free", "자유"),
                            ("food", "음식"),
                            ("bowling", "볼링"),
                            ("coding", "코딩"),
                        ],
                        max_length=10,
                        verbose_name="category",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일자"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
            ],
        ),
    ]
